### ISSUE TITLE
[Unit] Unit Milestone

### ISSUE THREAD

**Issue by Beanzilla** [Beanzilla/mindustry-hacked#7]
Complete the following:

- [x] Make Mass Assembler (a building which allows our units to be created)
- [x] Make Warhound (land)
- [ ] Make Nautical (sea)
- [ ] Make Thunder (air)
- [x] Overview
- [x] Released v0.2
